'use strict';

const puppeteer = require('puppeteer');
const epub = require('epub-gen');

const options = {
  title: 'The Legend of Harry Potter Schoolmaster',
  author: 'The Legend of Harry Potter Schoolmaster',
  output:
    './The Legend of Harry Potter Schoolmaster/The-Legend-of-Harry-Potter-Schoolmaster-101-150.epub',
  content: [],
};

// This is where we'll put the code to get around the tests.
const preparePageForTests = async (page) => {
  // Pass the User-Agent Test.
  const userAgent =
    'Mozilla/5.0 (X11; Linux x86_64)' +
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.39 Safari/537.36';
  await page.setUserAgent(userAgent);
};

const scrapepage = async (urls) => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox'],
  });
  for (let i = 0; i < urls.length; i++) {
    try {
      console.log('started', urls[i]);
      const page = await browser.newPage();
      await preparePageForTests(page);
      await page.goto(urls[i], { waitUntil: 'load' });
      //   await page.screenshot({
      //     path: './screenshot.jpg',
      //     type: 'jpeg',
      //     fullPage: true,
      //   });
      const chapter = await page.evaluate(() => {
        let title = document.querySelector('.main-title').innerText;
        let text = Array.from(
          document.querySelectorAll('.par.fontsize-16>p'),
          (element) => `<p>${element.innerText}</p>`
        );
        return {
          title: title,
          data: text.join(''),
        };
      });
      //   console.log('CHAPTER', chapter);
      options.content.push(chapter);
      await page.close();
      console.log('ended');
    } catch (error) {
      console.log(error);
    }
  }
  await browser.close();
};

const links = [
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-101-siskin-behind/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-102-peter-s-secret/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-103-silver-bullet-devil-net-and-dog-food/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-104-there-has-never-been-a-savior-6th/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-105-daily-prophet/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-106-bounty/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-107-2-world-cups/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-108-kanon-and-gold/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-109-chance-encounter/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-110-invisible-guardian/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-111-at-the-madam-morkin-robe-store/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-112-powerful-potion/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-113-survey-team/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-114-passenger-4/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-115-sorting-ceremony/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-116-top-3-tournament/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-117-dumbledore-s-inquiry/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-118-divination-teacher/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-119-animagus/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-120-protecting-magical-creatures-part-2/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-121-angry-snape/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-122-dark-magic/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-123-ancient-runic/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-124-tip-deformation-guide/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-125-work-in-school/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-126-boothbarton-and-durmstrang/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-127-familiar/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-128-s-p-e-w/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-129-warriors-of-hogwarts/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-130-1-snake-playing-crowd-who-doesn-t-know-the-truth/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-131-blood-man/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-132-failed-to-abstain-2nd/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-133-lost-game/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-134-unfulfilled-promise/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-135-meditation-basin/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-136-dumbledore-s-memories/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-137-ukrainian-iron-belly-dragon/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-138-check-wand/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-139-hogsmeade/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-140-contents-of-item-1/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-141-an-empty-office/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-142-4-fire-dragons/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-143-against-the-iron-belly/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-144-sleepy-dragon/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-145-tears/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-146-the-little-hand-that-appeared-quietly/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-147-score/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-148-durmstrang/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-149-for-the-greater-good/',
  'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-150-sleeping-dragon-do-not-disturb/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-151-potions-sequence-list/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-152-the-school-will-arrange-1-for-you/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-153-invite/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-154-christmas-gift/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-155-you-are-beautiful-today/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-156-christmas-dinner/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-157-christmas-ball/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-158-secret-in-the-garden/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/send-a-single-chapter-and-ask-for-monthly-pass/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-159-the-secret-of-cutting-edge-black-magic/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-160-horcrux/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/sorry-it-may-take-2-days-to-add/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-161-angry-unicorn/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-162-trial/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-163-veritaserum/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-164-hermione-who-appeared-suddenly/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-165-deep-dive/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-166-i-didn-t-have-to-choose-before/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-167-underwater-rescue/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-168-phoenix-singing/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/explain-a-little-bit/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-169-competition-is-over/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-170-horrible-difference/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-171-do-not-disturb/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-172-idiot/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-173-appointment/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-174-gift-for-astoria/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-175-the-death-of-crouch/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-176-project-3/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-177-double-glory/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-178-raze-little-hangleton/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-179-death-a-new-beginning/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-180-marashenko/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-181-li-daitao/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-182-jon-and-dumbledore/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-183-maze/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-184-confrontation/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/sorry-take-a-day-off/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-185-angry-minister/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-186-man-in-wooden-box/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-187-at-hogwarts/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-188-dumbledore-s-request/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-189-rise-of-the-dark-lord/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-190-eastleigh-road/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-191-golden-owl/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/just-say-a-few-words/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-192-the-great-deeds-of-the-dark-lord/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-193-new-identity/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-194-leviathan/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-195-arrive-in-durmstrang/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-196-iron-ring/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-197-mysterious-box/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-198-castle-among-the-mountains/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-199-madame-maxim-and-hagrid/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-200-the-unreliable-auror/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-201-overheard-conversation/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-202-dumbledore/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-203-murderer-potter/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-204-a-chance-encounter-in-xiaohuijin-district/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-205-home-visit/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-206-aunt-petunia-and-snape/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-207-the-story-of-petunia-evans/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-208-return-to-london/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-209-king-10-station/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-210-travel-on-the-train/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-211-coming-to-hogwarts/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-212-second-branch/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-213-new-school/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-214-protecting-magical-animals-class-teacher/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-215-dolores-umbridge/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-216-slytherin-s-common-room/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-217-barbo-tuber/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-218-umbridge-s-wrath/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-219-contradict/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-220-flitwick/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-221-3-predictions/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-222-prophetic-genius/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-223-meeting-in-the-forbidden-forest/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-224-of-course-i-chose-to-forgive-him/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-225-1-piece-of-advice/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-226-harry-the-terrified/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-227-senior-investigator-of-hogwarts/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-228-watched-castle/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-229-duties-of-senior-prosecutors/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-230-poor-trelawney/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/double-at-the-end-of-the-month-ask-for-a-monthly-pass/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-231-umbridge/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-332-hogsmeade-s-party/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-233-knights-of-walpers/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/thank-you-for-your-support-and-continue-to-ask-for-monthly-tickets/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-234-reveal-the-future/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-235-the-legacy-of-grindelwald/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-236-madame-petitfu-teahouse/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-237-strange-astoria/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-238-education-order-no-24/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-239-d-a/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-240-keep-for-inspection/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-241-death-eater-s-letter/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-242-blood-curse/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-243-the-departure-of-the-mad-eye/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-244-2-new-teachers/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-245-hagrid-is-back/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-246-trelawney/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-247-professor-scamander/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-248-the-2nd-d-a-party/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-249-astoria-s-talk/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-250-3rd-date/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-251-you-don-t-understand-anything/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-252-dumbledore-brother-and-sister-warning/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-253-is-your-father-okay/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-254-the-law-of-deformation-part-1/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-255-the-law-of-deformation-part-2/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-4-more-ask-for-monthly-pass/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-256-assault/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-257-st-mungo/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-258-neighbors-of-the-harts/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-259-forgotten-professor/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-260-panic/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-261-unexpected-letter/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/sorry-take-a-day-off-no-274/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-262-the-disguise-seen-through/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-263-1-forget-everything/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-264-headache/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-265-fugitives-informants-and-dating/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-266-horse-prophecy/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-267-ears-and-eyes/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-268-a-chance-encounter-in-front-of-a-tea-house/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-269-astoria-is-sick/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-270-ye-chuang-principal-s-office/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-271-i-caught-potter/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-272-you-umbridge-stray-dog/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-273-take-the-pot/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-274-injured/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-275-new-principal/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-276-the-cleaner-in-the-principal-s-office/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-277-hogwarts-principals/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-278-patrick-under-attack/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-279-the-missing-patrick/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-280-life-after-disappearance/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-281-jon-hart-s-philosophy-of-magic-part-1/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-282-jon-hart-s-philosophy-of-magic-part-2/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-283-leave-the-principal-s-office/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-284-astoria-is-back/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-286-hunt-down-the-half-blood-giant/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-287-angry-glop/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-287-harry-potter-s-dreamland/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-288-save-the-godfather-plan/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-289-wait-for-the-rabbit/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-290-interrogation/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-291-temptation-of-the-devil/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/292-i-need-your-help/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-293-for-the-greater-good/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-294-jon-s-plan/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-295-prediction-ball/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-296-the-order-of-the-phoenix-appears/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-297-the-battle-of-white-and-black/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-298-riddle-s-last-stroke/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-299-kill-him-barty/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-300-pig-head-bar/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-301-prophecy-magus/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-302-dumbledore-s-secret/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/may-be-broken-for-1-day-and-explain-1-prophecy-magus/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-303-salute-to-you/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-304-i-m-very-sorry/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-305-castle-selection-wizard/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-306-i-will-only-stand-on-the-side-of-the-winner/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-307-end-of-semester/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-308-black-and-white-robe/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-309-wait-for-the-rabbit/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-310-the-ruined-horcrux-happy-children-s-day-everyone/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-311-peverier-s-ring/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-312-resurrection-stone/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/subsection/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-313-minister-bones/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-314-phoenix-reborn-from-the-ashes/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/sorry-no-more-today/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-315-spider-s-tail-2-in-1/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-316-phoenix-iron-eater-and-owl-tonic/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/let-s-take-another-day/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-317-salvation-3/',
  //   'https://www.mtlnovel.com/the-legend-of-harry-potter-schoolmaster/chapter-318-invite/',
];

scrapepage(links).then((response) =>
  new epub(options).promise.then(() => console.log('Done'))
);
